/*
 * generated by Xtext 2.12.0
 */
package com.dslconsultancy.hierarchies


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HierarchyDslStandaloneSetup extends HierarchyDslStandaloneSetupGenerated {

	def static void doSetup() {
		new HierarchyDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
