/*
 * generated by Xtext 2.12.0
 */
package com.dslconsultancy.hierarchies.ide


/**
 * Use this class to register ide components.
 */
class HierarchyDslIdeModule extends AbstractHierarchyDslIdeModule {
}
